****************

Bug not show log of Pyqt5 : https://stackoverflow.com/questions/33736819/pyqt-no-error-msg-traceback-on-exit

****************

Dont show error with pyqt design :
# Back up the reference to the exceptionhook
sys._excepthook = sys.excepthook


def my_exception_hook(exctype, value, traceback):
    # Print the error and traceback
    print(exctype, value, traceback)
    # Call the normal Exception hook after
    sys._excepthook(exctype, value, traceback)
    sys.exit(1)

# Set the exception hook to our wrapping function
sys.excepthook = my_exception_hook

****************

define @pyqtSlot -> from PyQt5.QtCore import pyqtSlot

****************

pyuic5 -o ui_findandreplacedlg.py findandreplacedlg.ui
pyrcc5  -o qrc_resources.py resources.qrc